services:
    ajenbo.defaultgravatar.listener:
        class: ajenbo\defaultgravatar\event\main_listener
        arguments:
            - @config
            - @template
            - @user
            - %core.root_path%
        tags:
            - { name: event.listener }
    ajenbo.defaultgravatar.acplistener:
        class: ajenbo\defaultgravatar\event\acplistener
        arguments:
            - @user
        tags:
            - { name: event.listener }
